# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v1.x

pool:
  vmImage: ubuntu-latest

steps:
- task: CMake@1
  displayName: 'Setup cmake'

- script: |
    pwd
    cd build && cmake .. && make 
    ls -lht
  displayName: 'Run a multi-line script'
