# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v1.x

pool:
  vmImage: ubuntu-latest

steps:
- script: apt update && apt install -y cmake
  displayName: 'Run a one-line script'

- script: |
    pwd
    mkdir build && cd build && cmake .. && make 
    ls -lht
  displayName: 'Run a multi-line script'
